alter table public.skills add column source_name text;

insert into public.skills (slug, name, category, description, source_name, source, level, min_age_weeks, sort_order) values
  ('poutre','Poutre','novice','Marcher sur une planche surélevée de quelques centimètres.','Balance beam (walk on board a few inches off floor)','AKC Trick Dog','novice',8,1000),
  ('aboyer_sur_demande','Aboyer sur demande','novice','Donner de la voix au signal.','Bark on cue (“Speak”)','AKC Trick Dog','novice',8,1010),
  ('ramper','Ramper','novice','Sur le ventre, sur au moins trois longueurs de corps.','Crawl (dog on belly, crawls at least 3 body lengths)','AKC Trick Dog','novice',8,1020),
  ('rapporter','Rapporter','novice','Objet à 3 mètres, rapporté à moins d''un mètre.','Fetch it (ball, etc., 10 ft. away, bring to handler within 2 ft)','AKC Trick Dog','novice',8,1030),
  ('cherche','Cherche','novice','Trouver une friandise cachée sous un gobelet.','Find it (find treat or scent item hidden under 1 cup or object)','AKC Trick Dog','novice',8,1040),
  ('va_chercher_ton_objet','Va chercher ton objet','novice','Laisse, brosse ou jouet nommé.','Get your','AKC Trick Dog','novice',8,1050),
  ('monte_dedans','Monte dedans','novice','Entrer dans un carton ou un bac.','Get in (gets in box)','AKC Trick Dog','novice',8,1060),
  ('assis_dans_le_bac','Assis dans le bac','novice','S''asseoir une fois dans le bac.','Sits in box (on cue)','AKC Trick Dog','novice',8,1070),
  ('monte_dessus','Monte dessus','novice','Quatre pattes sur une plateforme basse.','Get on (gets on low platform or step - 4 paws)','AKC Trick Dog','novice',8,1080),
  ('signal_de_la_main','Signal de la main','novice','Un ordre au geste seul : assis, couché ou viens.','Hand signals (Choose one: down, sit, or come)','AKC Trick Dog','novice',8,1090),
  ('tape_m_en_cinq','Tape m''en cinq','novice','Patte levée contre la main.','High five','AKC Trick Dog','novice',8,1100),
  ('tiens','Tiens','novice','Garder un objet en gueule trois secondes.','Hold (3 seconds)','AKC Trick Dog','novice',8,1110),
  ('saute','Saute','novice','Par un cerceau bas ou par-dessus une barre basse.','Jump (thru a low hoop or over a low bar)','AKC Trick Dog','novice',8,1120),
  ('va_au_box','Va au box','novice','Entrer dans la caisse et y rester jusqu''au signal.','Kennel up (go in crate, stay in until released)','AKC Trick Dog','novice',8,1130),
  ('bisou','Bisou','novice','Museau posé sur la joue ou la main.','Kiss (point to cheek or back of hand)','AKC Trick Dog','novice',8,1140),
  ('pattes_dessus','Pattes dessus','novice','Deux pattes avant sur un tabouret bas.','Paws up (2 front paws on low stool or step)','AKC Trick Dog','novice',8,1150),
  ('pompes','Pompes','novice','Alterner assis et couché trois fois.','Push-ups (sit, down, sit, down, sit, down)','AKC Trick Dog','novice',8,1160),
  ('donne_la_patte','Donne la patte','novice','Poser la patte dans la main.','Shake hands','AKC Trick Dog','novice',8,1170),
  ('tourne','Tourne','novice','Un tour complet sur soi-même.','Spin in circle','AKC Trick Dog','novice',8,1180),
  ('touche','Touche','novice','Museau sur la main ou sur une cible.','Touch it (hand or target stick)','AKC Trick Dog','novice',8,1190),
  ('tunnel','Tunnel','novice','Traverser un tunnel d''agility ou de jeu.','Tunnel (agility tunnel or child’s tunnel)','AKC Trick Dog','novice',8,1200),
  ('equilibre_sur_ballon','Équilibre sur ballon','intermediate','Tenir en équilibre sur un ballon de proprioception.','Balance on ball or foam exercise peanut','AKC Trick Dog','intermediate',8,1210),
  ('ouvre_la_porte','Ouvre la porte','intermediate','Ouvrir une porte ou une portière de jouet.','Open door','AKC Trick Dog','intermediate',8,1220),
  ('friandise_en_equilibre','Friandise en équilibre','intermediate','Garder une friandise sur le nez ou la tête.','Balance treat on nose or head (e.g., dog biscuit)','AKC Trick Dog','intermediate',8,1230),
  ('ouvre_le_tiroir','Ouvre le tiroir','intermediate','Tirer sur une sangle pour ouvrir.','Open drawer (cloth pull)','AKC Trick Dog','intermediate',8,1240),
  ('porte','Porte','intermediate','Transporter un panier ou un objet.','Carry (such as basket or another object)','AKC Trick Dog','intermediate',8,1250),
  ('pattes_sur_le_bras','Pattes sur le bras','intermediate','Deux pattes avant posées sur ton bras.','Paws up (on handler’s arm)','AKC Trick Dog','intermediate',8,1260),
  ('attrape_au_vol','Attrape au vol','intermediate','Rattraper un jouet souple ou une friandise.','Catch (soft toy, soft ball, treat, etc.)','AKC Trick Dog','intermediate',8,1270),
  ('tire_la_corde','Tire la corde','intermediate','Tracter un jouet au bout d''une ficelle.','Pull a toy on a string or rope','AKC Trick Dog','intermediate',8,1280),
  ('ferme_la_porte','Ferme la porte','intermediate','Pousser la porte jusqu''à fermeture.','Close door','AKC Trick Dog','intermediate',8,1290),
  ('appuie_sur_le_bouton','Appuie sur le bouton','intermediate','Déclencher un son en appuyant.','Push button/key to make sound','AKC Trick Dog','intermediate',8,1300),
  ('ferme_le_tiroir','Ferme le tiroir','intermediate','Repousser le tiroir avec le museau ou la patte.','Close drawer','AKC Trick Dog','intermediate',8,1310),
  ('sors_l_objet','Sors l''objet','intermediate','Récupérer un objet dans une boîte.','Remove object from box/ toy mailbox','AKC Trick Dog','intermediate',8,1320),
  ('ramper_longuement','Ramper longuement','intermediate','Cinq longueurs de corps, leurre autorisé.','Crawl (at least 5 body lengths-may use food/toy lure)','AKC Trick Dog','intermediate',8,1330),
  ('sonne','Sonne','intermediate','Actionner une clochette montée sur support.','Ring bell, doorbell mounted on wood','AKC Trick Dog','intermediate',8,1340),
  ('rapporter_en_main','Rapporter en main','intermediate','Objet à 6 mètres, remis directement en main.','Fetch it (20 ft. away and deliver to hand)','AKC Trick Dog','intermediate',8,1350),
  ('roule','Roule','intermediate','Rouler complètement sur le dos.','Rollover','AKC Trick Dog','intermediate',8,1360),
  ('flyball','Flyball','intermediate','Courir, actionner la boîte, récupérer la balle.','Flyball (run to, push, get ball)','AKC Trick Dog','intermediate',8,1370),
  ('bonneteau','Bonneteau','intermediate','Désigner le bon gobelet parmi trois.','Shell game (“Find it” - treat or scent item under 1 of 3 cups)','AKC Trick Dog','intermediate',8,1380),
  ('jeu_d_occupation','Jeu d''occupation','intermediate','Manipuler un jeu interactif pour chien.','Game (manipulates interactive canine game)','AKC Trick Dog','intermediate',8,1390),
  ('fais_le_beau','Fais le beau','intermediate','Assis sur l''arrière-train, pattes avant levées.','Sit pretty (sit up or sit w/ head tilted)','AKC Trick Dog','intermediate',8,1400),
  ('va_me_chercher','Va me chercher','intermediate','Retrouver la personne qui s''est cachée.','Go find (handler hides, dog goes and finds)','AKC Trick Dog','intermediate',8,1410),
  ('balancoire','Balançoire','intermediate','Traverser une bascule d''agility.','Teeter totter (may use agility equip. in Intermediate)','AKC Trick Dog','intermediate',8,1420),
  ('va_a_ta_place','Va à ta place','intermediate','Rejoindre son tapis ou sa caisse à 3 mètres.','Go to your place (to bed/mat, crate from 10 ft.)','AKC Trick Dog','intermediate',8,1430),
  ('allume_la_lampe','Allume la lampe','intermediate','Toucher une lampe tactile.','Touch lamp','AKC Trick Dog','intermediate',8,1440),
  ('trois_signaux_de_la_main','Trois signaux de la main','intermediate','Trois ordres au geste seul.','Hand signals (Sit, down, come, stand. Total of 3.)','AKC Trick Dog','intermediate',8,1450),
  ('fais_coucou','Fais coucou','intermediate','Agiter une patte en l''air.','Wave good-bye/hello','AKC Trick Dog','intermediate',8,1460),
  ('tete_basse','Tête basse','intermediate','Poser la tête au sol ou sur un support.','Head down','AKC Trick Dog','intermediate',8,1470),
  ('slalom','Slalom','intermediate','Six piquets, leurre autorisé.','Weave poles (may use food or toy lure - 6 weave poles)','AKC Trick Dog','intermediate',8,1480),
  ('marche_au_pied','Marche au pied','intermediate','Au pied, avec assis automatique à l''arrêt.','Heeling with automatic sit','AKC Trick Dog','intermediate',8,1490),
  ('plateau_instable','Plateau instable','intermediate','Tenir sur une planche qui bascule.','Wobble board','AKC Trick Dog','intermediate',8,1500),
  ('saute_dans_le_cercle','Saute dans le cercle','intermediate','Franchir le cercle formé par tes bras.','Jump through handler’s circled arms','AKC Trick Dog','intermediate',8,1510),
  ('slalom_entre_les_jambes','Slalom entre les jambes','intermediate','Zigzaguer entre tes jambes à l''arrêt.','Leg weave (weave around handler’s legs)','AKC Trick Dog','intermediate',8,1520),
  ('recule','Recule','advanced','Marcher en arrière en ligne droite.','Back up (walk backwards)','AKC Trick Dog','advanced',8,1530),
  ('pivot','Pivot','advanced','Pattes avant sur un disque, l''arrière tourne.','Pivot (paws on disk)','AKC Trick Dog','advanced',8,1540),
  ('friandise_lancee','Friandise lancée','advanced','Faire sauter la friandise du nez pour l''attraper.','Balance treat on nose, flip to eat (when told “OK”)','AKC Trick Dog','advanced',8,1550),
  ('fais_le_mort','Fais le mort','advanced','Se coucher sur le flanc et rester immobile.','Play dead (faint, sleep, etc.)','AKC Trick Dog','advanced',8,1560),
  ('tonneau','Tonneau','advanced','Faire rouler un tonneau ou tenir dessus.','Barrel (roll with 2 paws, or stand on with 4)','AKC Trick Dog','advanced',8,1570),
  ('tire_le_sac','Tire le sac','advanced','Tracter un sac chargé.','Pulls a bag with objects','AKC Trick Dog','advanced',8,1580),
  ('basket','Basket','advanced','Mettre une balle dans un panier.','Basketball','AKC Trick Dog','advanced',8,1590),
  ('enleve_la_chaussure','Enlève la chaussure','advanced','Retirer un chausson ou une chaussure.','Remove handler’s slipper, shoe','AKC Trick Dog','advanced',8,1600),
  ('reverence','Révérence','advanced','Avant au sol, arrière-train levé.','Bow (as in “Take a bow”, curtsy)','AKC Trick Dog','advanced',8,1610),
  ('rampe_en_arriere','Rampe en arrière','advanced','Reculer en rampant sur trois longueurs.','Retreat -crawl backwards 3 body lengths','AKC Trick Dog','advanced',8,1620),
  ('tourne_a_droite_a_gauche','Tourne à droite, à gauche','advanced','Un tour dans chaque sens sur demande.','Circle right, circle left','AKC Trick Dog','advanced',8,1630),
  ('ramasse_un_objet_plat','Ramasse un objet plat','advanced','Saisir une carte posée à plat au sol.','Retrieve - flat item, flat surface (e.g.,credit card from floor)','AKC Trick Dog','advanced',8,1640),
  ('cache_tes_yeux','Cache tes yeux','advanced','Poser une patte sur les yeux.','Cover your eyes (paw over eyes)','AKC Trick Dog','advanced',8,1650),
  ('tour_inverse','Tour inversé','advanced','Contourner la personne dans l''autre sens.','Reverse circles around handler','AKC Trick Dog','advanced',8,1660),
  ('mets_toi_sous_la_couverture','Mets-toi sous la couverture','advanced','Se glisser sous une couverture.','Cover-up with blanket','AKC Trick Dog','advanced',8,1670),
  ('fais_ta_priere','Fais ta prière','advanced','Museau entre les pattes posées sur un support.','Say your prayers','AKC Trick Dog','advanced',8,1680),
  ('danse','Danse','advanced','Se déplacer sur les pattes arrière.','Dance/moonwalk','AKC Trick Dog','advanced',8,1690),
  ('discrimination_d_odeur','Discrimination d''odeur','advanced','Retrouver l''objet marqué parmi cinq.','Scent articles (choose from 5)','AKC Trick Dog','advanced',8,1700),
  ('l_air_gene','L''air gêné','advanced','Cacher le museau derrière la patte.','Embarrassed','AKC Trick Dog','advanced',8,1710),
  ('ebroue_toi','Ébroue-toi','advanced','S''ébrouer sur demande.','Shake (as in to shake off water)','AKC Trick Dog','advanced',8,1720),
  ('va_te_cacher','Va te cacher','advanced','Se glisser sous une table.','Go hide (get under table, etc.)','AKC Trick Dog','advanced',8,1730),
  ('chante','Chante','advanced','Vocaliser sur demande.','Sing, talk','AKC Trick Dog','advanced',8,1740),
  ('assis_ou_couche_a_distance','Assis ou couché à distance','advanced','À 5 mètres, sans se rapprocher.','Sit or down at distance (15 ft.)','AKC Trick Dog','advanced',8,1750),
  ('cache_ta_tete','Cache ta tête','advanced','Glisser la tête sous un coussin.','Hide your head (under blanket, pillow, etc.)','AKC Trick Dog','advanced',8,1760),
  ('beau_facon_lassie','Beau, façon Lassie','advanced','Assis beau avec une patte repliée.','Sit pretty, add Lassie pose','AKC Trick Dog','advanced',8,1770),
  ('reconnaitre_un_jouet','Reconnaître un jouet','advanced','Choisir le bon jouet parmi trois, par son nom.','Identify toy by name (out of 3)','AKC Trick Dog','advanced',8,1780),
  ('sourire','Sourire','advanced','Montrer les dents sans tension.','Smile','AKC Trick Dog','advanced',8,1790),
  ('saute_dans_les_bras','Saute dans les bras','advanced','Sauter et être rattrapé.','Jump into handler’s arms','AKC Trick Dog','advanced',8,1800),
  ('museau_ecrase','Museau écrasé','advanced','Presser la truffe contre une vitre.','Smoosh (press face on plexiglass)','AKC Trick Dog','advanced',8,1810),
  ('saute_par_dessus_le_dos','Saute par-dessus le dos','advanced','Franchir ton dos.','Jump over handler’s back','AKC Trick Dog','advanced',8,1820),
  ('eternue','Éternue','advanced','Éternuer sur demande.','Sneeze','AKC Trick Dog','advanced',8,1830),
  ('pose_lassie','Pose Lassie','advanced','Assis beau, une patte repliée.','Lassie pose (sit pretty, bent paw)','AKC Trick Dog','advanced',8,1840),
  ('sors_un_mouchoir','Sors un mouchoir','advanced','Extraire un mouchoir de la boîte et l''apporter.','Tissue out of box (and bring to handler)','AKC Trick Dog','advanced',8,1850),
  ('slalom_en_marchant','Slalom en marchant','advanced','Zigzaguer entre tes jambes pendant que tu avances.','Leg weave, handler walks','AKC Trick Dog','advanced',8,1860),
  ('range_tes_jouets','Range tes jouets','advanced','Rapporter les jouets dans le bac.','Toys (take to and drop in box)','AKC Trick Dog','advanced',8,1870),
  ('allume','Allume','advanced','Actionner une lampe à pile.','Light (turn on battery operated light)','AKC Trick Dog','advanced',8,1880),
  ('passe_dessous','Passe dessous','advanced','Passer sous toi à quatre pattes.','Under handler (handler on hands and knees)','AKC Trick Dog','advanced',8,1890),
  ('fais_ton_lit','Fais ton lit','advanced','Tirer la couverture sur le couchage.','Make your bed','AKC Trick Dog','advanced',8,1900),
  ('marche_sur_deux_pattes','Marche sur deux pattes','advanced','Avancer debout, sans appui.','Walk on hind legs (paws may not be on handler’s arm)','AKC Trick Dog','advanced',8,1910),
  ('ouvre_et_rapporte','Ouvre et rapporte','advanced','Ouvrir un meuble et en sortir un objet.','Open door (mailbox toy refrigerator) get object','AKC Trick Dog','advanced',8,1920),
  ('slalom_sans_leurre','Slalom sans leurre','advanced','Six piquets, sans guidage.','Weave poles (no lures)','AKC Trick Dog','advanced',8,1930),
  ('paye','Paye','advanced','Rapporter un billet ou une pièce.','Pay for it (fetch and bring money)','AKC Trick Dog','advanced',8,1940),
  ('pickpocket','Pickpocket','advanced','Retirer un objet de ta poche en mouvement.','Pick pocket (as handler moves)','AKC Trick Dog','advanced',8,1950),
  ('reponds_a_la_question','Réponds à la question','performer','Aboyer ou hocher en réponse à une question.','Answer questions (‘Do you like','AKC Trick Dog','performer',8,1960),
  ('balle_dans_le_cone','Balle dans le cône','performer','Lâcher la balle dans une ouverture étroite.','Ball into small cone (Drop ball into opening)','AKC Trick Dog','performer',8,1970),
  ('bulles','Bulles','performer','Souffler des bulles dans l''eau.','Blowing bubbles','AKC Trick Dog','performer',8,1980),
  ('sors_des_jouets','Sors des jouets','performer','Enfoui sous les jouets, sortir la tête au signal.','Buried under toys, poke head out on cue','AKC Trick Dog','performer',8,1990),
  ('porte_sur_le_dos','Porte sur le dos','performer','Transporter une peluche sur le dos.','Carry stuffed animal on back','AKC Trick Dog','performer',8,2000),
  ('croise_les_pattes','Croise les pattes','performer','Poser une patte sur l''autre.','Cross paws- one, then the other','AKC Trick Dog','performer',8,2010),
  ('fais_semblant_de_creuser','Fais semblant de creuser','performer','Gratter dans le vide sur demande.','Dig - pretend to dig','AKC Trick Dog','performer',8,2020),
  ('huit','Huit','performer','Dessiner un huit autour de deux repères, seul.','Figure 8 - dog does without handler','AKC Trick Dog','performer',8,2030),
  ('dans_la_valise','Dans la valise','performer','Entrer dans la valise et refermer le couvercle.','Get in suitcase and close lid','AKC Trick Dog','performer',8,2040),
  ('saut_dans_le_cerceau_de_papier','Saut dans le cerceau de papier','performer','Traverser un cerceau tendu de papier.','Jump through tissue hoop','AKC Trick Dog','performer',8,2050),
  ('sautille_de_joie','Sautille de joie','performer','Sauter sur place en frétillant.','Jump up and down/wiggle with excitement','AKC Trick Dog','performer',8,2060),
  ('au_lit_sur_le_dos','Au lit, sur le dos','performer','Se retourner ventre en l''air dans le couchage.','In bed, turns so belly is up','AKC Trick Dog','performer',8,2070),
  ('echelle','Échelle','performer','Marcher sur les montants d''une échelle au sol.','Ladder- (small wooden on ground, walk on side rails)','AKC Trick Dog','performer',8,2080),
  ('leve_la_patte','Lève la patte','performer','Mimer le marquage sur une borne.','Lift leg -pretend - fire hydrant','AKC Trick Dog','performer',8,2090),
  ('boitille','Boitille','performer','Avancer en tenant une patte levée.','Limping','AKC Trick Dog','performer',8,2100),
  ('oui_ou_non','Oui ou non','performer','Hocher ou secouer la tête.','Nod or shake head (yes/no)','AKC Trick Dog','performer',8,2110),
  ('dessus_dessous','Dessus dessous','performer','Sauter par-dessus puis passer dessous.','Over & Under handler (jumps over, runs under)','AKC Trick Dog','performer',8,2120),
  ('apporte_le_telephone','Apporte le téléphone','performer','Réagir à la sonnerie et rapporter l''appareil.','Phone (hears ring at distance, brings to handler)','AKC Trick Dog','performer',8,2130),
  ('traine_le_sac','Traîne le sac','performer','Tracter un sac d''objets sur une distance.','Pulls (drags) bag of objects','AKC Trick Dog','performer',8,2140),
  ('lancer_d_anneaux','Lancer d''anneaux','performer','Placer au moins trois anneaux sur un piquet.','Ring toss (at least 3 rings)','AKC Trick Dog','performer',8,2150),
  ('tourne_autour','Tourne autour','performer','Faire des cercles autour d''une personne ou d''un poteau.','Runs circles around human or post','AKC Trick Dog','performer',8,2160),
  ('beau_avec_un_objet','Beau avec un objet','performer','Assis beau en tenant un objet dans la patte.','Sit pretty while holding something with paw (flag)','AKC Trick Dog','performer',8,2170),
  ('deplacement_lateral','Déplacement latéral','performer','Avancer de côté en même temps que toi.','Side pass (dog & handler move laterally)','AKC Trick Dog','performer',8,2180),
  ('football','Football','performer','Pousser la balle dans le but.','Soccer (push ball into goal)','AKC Trick Dog','performer',8,2190),
  ('essuie_tes_pattes','Essuie tes pattes','performer','Frotter les pattes sur le paillasson.','Wipe feet on mat (modified dog)','AKC Trick Dog','performer',8,2200)
on conflict (slug) do nothing;
